Add an example for MultiNodeWeightedSampler
pytorch/data pull request #1385
Opened 2024-12-07 01:06 UTC by ramanishsingh

Added a very simple example for showing the functionality for MultiNodeWeightedSampler
Fixes #1352
=

2024-12-08 02:26 UTC, divyanshk commented
Super Duper Nit: can you add a space between the comments' hashtag and the first letter (makes things consistent and neater), thank you :-)

2024-12-08 02:28 UTC, divyanshk commented
For the first cell, we can make the contents show up in a markdown or text cell? instead of comments in a code cell

2024-12-08 02:30 UTC, divyanshk commented
Also, the three core lines of the notebook (sampler -> batcher -> loader) can be made to be in one cell? wdyt

2024-12-08 02:32 UTC, divyanshk approved these changes
Overall LGTM! Added some minor formatting requests.

2024-12-11 17:53 UTC, divyanshk commented
Is this ready to land ? @ramanishsingh @andrewkho

2024-12-11 18:44 UTC, andrewkho commented
Not yet, I think it can be simplified

2024-12-11 18:57 UTC, ramanishsingh commented
> Not yet, I think it can be simplified
@andrewkho which parts do you think are still convoluted?

2024-12-11 19:22 UTC, andrewkho commented
Whoops sorry I thought this was the RoundRobin sampler diff, let me have another look

2024-12-11 19:53 UTC, andrewkho commented on examples/nodes/multi_dataset_weighted_sampling.ipynb
> +    "### In this notebook, we will explore the usage of MultiNodeWeightedSampler in torchdata.nodes\n",
ditto here 
```suggestion
    "In this notebook, we will explore the usage of MultiNodeWeightedSampler in torchdata.nodes\n",
```

2024-12-11 19:54 UTC, andrewkho commented on examples/nodes/multi_dataset_weighted_sampling.ipynb
> +    "### In this notebook, we will explore the usage of MultiNodeWeightedSampler in torchdata.nodes\n",
Add a title though, eg 
```suggestion
    "#MultiNodeWeightedSampler example\n",
    "In this notebook, we will explore the usage of MultiNodeWeightedSampler in torchdata.nodes\n",
```

2024-12-11 19:54 UTC, andrewkho commented on examples/nodes/multi_dataset_weighted_sampling.ipynb
> +    "train_loader = Loader(multi_node_sampler)"
drop the train

2024-12-11 19:56 UTC, andrewkho commented on examples/nodes/multi_dataset_weighted_sampling.ipynb
> +    "#### If we fetch more items, the fractions will asymptotically reach the provided weights."
These don't need to be subheadings either

2024-12-11 19:57 UTC, andrewkho commented on examples/nodes/multi_dataset_weighted_sampling.ipynb
> +    "#### If we fetch more items, the fractions will asymptotically reach the provided weights."
actually I don't think we need this section at all, it seems a bit redundant. You can just use 100k in the cell above

2024-12-11 19:57 UTC, andrewkho requested changes
Few minor comments, but otherwise looking good!

2024-12-11 20:37 UTC, andrewkho approved these changes
gogogo

2024-12-12 14:46 UTC, merged