Fix is_local for paths starting with `az://`
pytorch/data pull request #849
Opened 2022-10-21 15:15 UTC by mpfirrmann

Signed-off-by: Marco Pfirrmann <marco.pfirrmann@tngtech.com>

Fixes #840. 
The module used to extract the protocol does not differentiate between `abfs://` and `az://` paths, always returning `abfs`. This fix adds `az` to the protocol list to be checked.

2022-10-21 15:27 UTC, ejguan reviewed
Thank you. Changes look good. Have you verified it working properly with the script in the issue. Could you please add a test [here](https://github.com/pytorch/data/blob/main/test/test_remote_io.py)?

2022-10-21 17:16 UTC, NivekT reviewed
Thanks for opening this PR. I agree testing this behavior will be helpful.

2022-11-11 22:56 UTC, NivekT approved these changes
The test LGTM!

2022-11-11 22:58 UTC, NivekT requested changes
The test LGTM but we need to either install `adlfs` or skip it when `adlfs` is not available. The former is probably best.

2022-11-16 14:43 UTC, mpfirrmann commented
> The test LGTM but we need to either install `adlfs` or skip it when `adlfs` is not available. The former is probably best.

I added the `adlfs` package to `test/requirements.txt` and it should be installed by the testing workflows.

2022-11-16 21:04 UTC, closed without merging